# Generated by Django 3.2.2 on 2021-05-13 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Company name')),
                ('position', models.CharField(max_length=70, verbose_name='Position')),
                ('desc', models.TextField(verbose_name='Description')),
                ('adress', models.CharField(max_length=70, verbose_name='Adress of company')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact data')),
                ('date', models.DateTimeField(verbose_name='Date of placing')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=70, verbose_name='Speciality')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Gender')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('about', models.TextField(verbose_name='About')),
                ('experience', models.IntegerField(verbose_name='Years of experience')),
                ('date', models.DateTimeField(verbose_name='Date of placing')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
