# Generated by Django 3.2.2 on 2021-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.TextField(default='Salary not specified', verbose_name='Salary'),
        ),
    ]
