# Generated by Django 3.2.2 on 2021-05-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacancy_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='about',
            new_name='desc',
        ),
    ]
